project:
  type: website
  output-dir: "."

website:
  title: "Marcus Smith"
  navbar:
    pinned: true
    left:
      - text: Project
        href: project.qmd
      - text: Blog
        href: blog-listing.qmd
      - text: R-Basics
        href: danl-200-quarto-ms.qmd
  page-footer: 
    center: "Powered with GitHub and Quarto<br>© marcussmith/2024"

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    mainfont: system-ui; 
    highlight-style: atom-one
    css: styles.css
    toc: false
    include-after-body: target_blank.html
    
